### ISSUE TITLE
Does this code work with a non power of 2 number of keys?

### ISSUE THREAD

**Issue by bitbugprime** [fredjarlier/mpiSORT#1]
The requirement for an exact power of two number of keys makes bitonic sorting useless in nearly all cases.

**Comment by fredjarlier** [comment]
It works whatever the number of keys. We complete the keys internally to fit a power of 2 and remove extras at the end.

**Comment by bitbugprime** [comment]
> It works whatever the number of keys. We complete the keys internally to fit a power of 2 and remove extras at the end.

So if you have, say, ~600 million keys you add ~400 million fake keys? That seems like a horrible amount of overhead compared to, say, a radix sort that didn't need the extra 400 million keys. How can a bitonic sort be efficient with such overhead?

**Comment by fredjarlier** [comment]
Because with bitonic we reason in log complexity and log(6e8) is not far from log(10e8) even for the squares. So you won't see noticeable difference in time. From my knowledge and though the radix sort is very good method it has a linear complexity even with parallelisation. 

But I agree it incurs an overhead in memory and in that case the memory needed to store the keys will double. This is why it is important to take the right amount of memory according to the RAM available per CPU and the size of the SAM file. The CPU must be a power of 2 it is the only drawback of the method.

**Comment by fredjarlier** [comment]
The project has moved. Please now consider this link for further question

https://github.com/bioinfo-pf-curie

Thanks

frederic
